name: CI

on: 
  push:
    branches:
    - hexo
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v1
      with:
        ref: hexo
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: install
      run: |
        npm install hexo-cli hexo-deployer-git -g
        npm install
        git config --global user.email "liwei2633@163.com"
        git config --global user.name "monkeyWie"
        hexo clean
        hexo d